candidates:
- Luffy
- BlackBeard
- Shanks
compiler:
  solc:
    remappings:
    - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'
dependencies:
- OpenZeppelin/openzeppelin-contracts@4.4.2
deployedContract:
  deployedABI: 'you will get ur deployment abi here'
  deployedAddress: 'you will get your address here when you deploy your contract'
